### ISSUE TITLE
Cloud-Config Fleet Security Settings

### ISSUE THREAD

**Issue by micahasmith** [coreos/fleet#1075]
I'm trying to write up how to secure CoreOS/fleet/etcd.

It looks like some etcd cert settings need specified for fleet as well.

Does the following cloud-config seem to specify them correctly?

``` yaml
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    # WARNING: replace each time you 'vagrant destroy'
    #discovery: https://discovery.etcd.io/7005dd479484de7f
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001

    # configure files for etcd security
    ca-file: /etc/etcd/printio.pem
    key-file: /etc/etcd/printio.key.insecure
    cert-file: /etc/etcd/printio.crt
    peer-key-file: /etc/etcd/printio.key.insecure
    peer-cert-file: /etc/etcd/printio.crt
    peer-ca-file: /etc/etcd/ca.crt
  fleet:
    public-ip: $public_ipv4
    # !! this is the section i'm interested in validating !!
    etcd-ca-file: /etc/etcd/printio.pem
    etcd-keyfile: /etc/etcd/printio.key.insecure
    etcd-certfile: /etc/etcd/printio.crt
```

Are there other security settings that are fleet specific that I should look into?

Thanks--
