### ISSUE TITLE
Cluster design "Production Cluster with Central Services" doesn't work correctly

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#1106]
Originally reported by @Stujordan at https://github.com/coreos/bugs/issues/252:

Hi,

we have deployed a 3-node etcd cluster and several workers as per the "Production Cluster with Central Services" example. Everything works fine so long as the first etcd (leader) node in the etcd_servers list is up:

```
coreos:
  fleet:
    metadata: "role=worker,cabinet=two,disk=spinning"
    etcd_servers: "http://10.0.0.101:4001,http://10.0.0.102:4001,http://10.0.0.103:4001,http://10.0.0.104:4001,http://10.0.0.105:4001"
```

As soon as 10.0.0.101 is offline the workers seem to go into a loop trying to contact 101 and never try and contact to 102. If we manually rearrange the etcd_servers list on the worker and restart fleet the worker re-joins.

The error logged in the worker fleet journal is:

```
Jan 27 15:51:18 coreos-worker fleetd[544]: INFO client.go:278: Failed getting response from http://10.0.0.101:4001/: cancelled
```

over and over. I have tested this on both stable and beta channels and the same problem occurs.
