### ISSUE TITLE
fleetctl status cannot find running unit shown in list-units

### ISSUE THREAD

**Issue by ChimeraCoder** [coreos/fleet#1208]
I ran into this issue when testing out a 3-machine cluster on DigitalOcean using the alpha build (which is the default on the [Digital Ocean setup guide](https://coreos.com/docs/running-coreos/cloud-providers/digitalocean/#via-the-api).

Executing the steps on the [Quickstart](https://coreos.com/docs/quickstart/) results in a seemingly-inconsistent state. 

Running `fleetctl load hello.service` and `fleetctl start hello.service` causes the service to be started. The unit is visible with `fleetctl status hello.service` on the other two machines in the cluster, but *not* on the original machine, even though it is shown in `fleetctl list-units` and `fleetctl list-unit-files` on the original machine. (`docker ps` and `systemctl status hello.service`)

While debugging this [on IRC](https://botbot.me/freenode/coreos/2015-04-30/?msg=38018609&page=9) with @robszumski, we found an error in the `cloud-config` on the Quickstart (fixed in https://github.com/coreos/docs/pull/494), but fixing that didn't solve this issue.

![screenshot - 04302015 - 04 17 31 pm](https://cloud.githubusercontent.com/assets/376414/7423655/50e8f400-ef65-11e4-8ed1-3b3af8e293dd.png)

This was fairly reproducible; wiping and reprovisioning the machines yielded it consistently for me.

Below is the cloud-config used (copied almost exactly from the Quickstart and DigitalOcean guide, except for the aforementioned fix):

````
#cloud-config

ssh_authorized_keys:
    - ssh-rsa AAAA.... #(ommitted)
coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the intial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/24213cbe5c58921b22607da2a9ba151e
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
````

````sh
#! /bin/sh
set -e

curl --request POST "https://api.digitalocean.com/v2/droplets" \
     --header "Content-Type: application/json" \
     --header "Authorization: Bearer $TOKEN" \
     --data '{
      "region":"nyc3",
      "image":"coreos-alpha",
      "size":"512mb",
      "name":"core-1",
      "private_networking":true,
      "ssh_keys":['$SSH_KEY_ID'],
      "user_data": "'"$(cat cloud-config.yml | sed 's/"/\\"/g')"'"
}'

curl --request POST "https://api.digitalocean.com/v2/droplets" \
     --header "Content-Type: application/json" \
     --header "Authorization: Bearer $TOKEN" \
     --data '{
      "region":"nyc3",
      "image":"coreos-alpha",
      "size":"512mb",
      "name":"core-2",
      "private_networking":true,
      "ssh_keys":['$SSH_KEY_ID'],
      "user_data": "'"$(cat cloud-config.yml | sed 's/"/\\"/g')"'"
}'

curl --request POST "https://api.digitalocean.com/v2/droplets" \
     --header "Content-Type: application/json" \
     --header "Authorization: Bearer $TOKEN" \
     --data '{
      "region":"nyc3",
      "image":"coreos-alpha",
      "size":"512mb",
      "name":"core-3",
      "private_networking":true,
      "ssh_keys":['$SSH_KEY_ID'],
      "user_data": "'"$(cat cloud-config.yml | sed 's/"/\\"/g')"'"
}'
