### ISSUE TITLE
Fleetd still refer to etcd old port 4001, although I am using etcd2

### ISSUE THREAD

**Issue by zxcvbn97** [coreos/fleet#1249]
Is there anyway to get rid of these log messages? 

> Jun 13 08:43:15 moon fleetd[591]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused

My etcd configuration

> etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: https://discovery.etcd.io/{{ token }}
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://{{ ip }}:2379
    initial-advertise-peer-urls: http://{{ ip }}:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://{{ ip }}:2380

**Comment by Vinceveve** [comment]
- name: fleet.service
      command: start
      content: |
        [Unit]
        Description=fleet daemon
        Wants=etcd2.service
        After=etcd2.service
        Wants=fleet.socket
        After=fleet.socket
        [Service]
        Environment="FLEET_ETCD_SERVERS=http://127.0.0.1:4001"
        Environment="FLEET_METADATA=mymeta"
        ExecStart=/usr/bin/fleetd
        Restart=always
        RestartSec=10s
```

**Comment by crawford** [comment]
You should use a drop-in for this.

```yaml
#cloud-config

coreos:
  units:
    - name: fleet.service
      drop-ins:
        - name: port.conf
          content: |
            [Service]
            Environment="FLEET_ETCD_SERVERS=http://127.0.0.1:2379"
```

**Comment by crawford** [comment]
Actually, the fleet section supports this directly. It would be even easier to just write:

```yaml
#cloud-config

coreos:
  fleet:
    etcd_servers: "http://127.0.0.1:2379"
```

**Comment by svparijs** [comment]
I had something similar turns out that I needed to change:
```yaml
  units:
    - name: etcd.service
      command: start
```
Into:
```yaml
  units:
    - name: etcd2.service
      command: start
```
Note the etcd2!
