### ISSUE TITLE
fleet needs to be restarted on machine reboot

### ISSUE THREAD

**Issue by chr0n1x** [coreos/fleet#1347]
On machine reboot, manual or OS update, my machines fail to join the fleet cluster.

```
core@foo ~ $ systemctl cat fleet
# /usr/lib64/systemd/system/fleet.service
[Unit]
Description=fleet daemon

After=etcd.service
After=etcd2.service

Wants=fleet.socket
After=fleet.socket

[Service]
ExecStart=/usr/bin/fleetd
Restart=always
RestartSec=10s

# /run/systemd/system/fleet.service.d/20-cloudinit.conf
[Service]
Environment="FLEET_ETCD_SERVERS=http://fleet-server.net:2379"
Environment="FLEET_METADATA=role=core"
core@foo ~ $ fleetctl --version
fleetctl version 0.10.2
```

CoreOS version `723.3.0`

On boot or system update, I get something like this:

```
core@foo ~ $ fleetctl list-machines
MACHINE		IP	METADATA
ac11ff8f...	-	-
```

Once I `systemctl restart fleet`:

```
core@foo ~ $ fleetctl list-machines
MACHINE		IP		METADATA
c6a2461b...	-	role=core
e7958848...	-	role=core
eded16ed...	-	role=core
f360c748...	-	role=core
ac11ff8f...	-	role=core
```

Any idea as to what I could be doing wrong?

**Comment by chr0n1x** [comment]
ping @jonboulle @wuqixuan

**Comment by philips** [comment]
@chr0n1x Is etcd2 getting started on boot? What is in your cloud-config? My hunch is something is something isn't getting started correctly. Also, can you gather up logs for fleet and etcd and upload them to gist? `journalctl _EXE=/usr/bin/etcd _EXE=/usr/bin/etcd2 _EXE=/usr/bin/fleetd`

**Comment by chr0n1x** [comment]
@philips cloud-config is pretty simple:

```
coreos:
  update:
    group: stable
    server: https://public.update.core-os.net/v1/update/
  units:
    - name: fleet.service
      command: start
    - name: etcd.service
      command: start
```
