### ISSUE TITLE
Implement support for self-signed CA / Certificates

### ISSUE THREAD

**Issue by noahlh** [coreos/fleet#837]
Took me a bit to track this down, but here's what I've discovered.

Goal:  Have etcd running securely using TLS certificates for transport & authentication, and allow fleet & fleetctl to connect accordingly.

Problem:  While fleet supports the definition of etcd_cafile, etcd_keyfile, and etcd_certfile, when using a self-signed CA file (or otherwise non-authoritative CA, i.e. CAcert), fleet fails to connect and throws a `x509: certificate signed by unknown authority` error.

Cause:  According to this:

http://golang.org/src/pkg/crypto/x509/root_unix.go

It looks like Go is using `/etc/ssl/certs/ca-certificates.crt` as the authoritative source of CA files.  So even if you add your CA file hash symlink to /etc/ssl/certs (see @brianredbeard 's post here:  https://groups.google.com/d/msg/coreos-user/5LlB9d_cFLA/ANtQtOXkdlwJ ) , which satisfies openssl (and curl), fleet still complains.

Temporary solution:   My extremely hackey temporary solution for securing etcd & fleet -- 
1.  Generate certificates using [etcd-ca](https://github.com/coreos/etcd-ca/blob/master/Documentation/work_with_etcd.md).
2.  Install certificates as per [Customizing the etcd Unit](https://coreos.com/docs/distributed-configuration/customize-etcd-unit/)
3.  Add the fleet environment variables to `cloud-config`:

```
coreos:
  fleet:
      ...snip...
       etcd_ca_file: "/path/to/ca.crt"
       etcd_certfile: "/path/to/server.crt"
       etcd_keyfile: "/path/to/server.key"
       etcd_servers: "https://127.0.0.1:4001"
```
1.  Somehow get your self-signed `ca.crt` into `/etc/ssl/certs/ca-certificates.crt`.  Not sure what the best way to do this, since it's just a symlink to /usr/share, which is read-only.  For now, I'm just clobbering the file with my own version with my CA appended.
2.  Fleet loads up nicely.  Then, set the environment variables to point to the proper endpoint (https) and the same ca, cert and key for fleetctl and voila, secure everything.

**Comment by psi-4ward** [comment]
Seems cloudinit dont support `etcd_ca_file` key
```
node01 coreos-cloudinit[576]: line 28: warning: unrecognized key "etcd_ca_file"
```

```
  fleet:
    etcd_servers: "https://123.123.123.123:4001"
    endpoint: "https://123.123.123.123:4001"
    etcd_ca_file: "/etcd-certs/ca.crt"
    etcd_certfile: "/etcd-certs/key.crt"
    etcd_keyfile: "/etcd-certs/key.key"
```
